### ISSUE TITLE
No error on 'privacyideaserver' => 'https://www.valid-domain.com/invalid-path and able to login with any combination.

### ISSUE THREAD

**Issue by vDorst** [privacyidea/simplesamlphp-module-privacyidea#1]
I was playing with simplesamlphp and this modules.
But I this configure my 'privacyideaserver' server wrong. right domain but non existing path
I allowed me to login without an error. 
Any username and password is accepted.
But no attribures returns.

simplesamlphp (1.13.2) from ubuntu 15_10.

**Comment by cornelinux** [comment]
This sounds evil.
In case of an invalid path, an exception due to failing json decoding should be raised.

I will look into this.

Probably we need to revert the logic.

**Comment by cornelinux** [comment]
@vDorst please check out. I was able to reproduce the problem on my system. The new commit fixed this.
