### ISSUE TITLE
Image linked from Google

### ISSUE THREAD

**Issue by koenr** [privacyidea/simplesamlphp-module-privacyidea#107]
May I suggest to replace the link to the background image in simplesamlphp-module-privacyidea/themes/google/css/google.css line 32 that links to https://ssl.gstatic.com/accounts/ui/avatar_2x.png with a link to an image available in the plugin.

**Comment by lukasmatusiewicz** [comment]
Hi, @koenr did you mean that the image for security reasons should be set in the plugin, or do you mean an option that allows you to link your own avatar?

**Comment by lukasmatusiewicz** [comment]
ok. thank you for your answer.
