### ISSUE TITLE
Attributes shown during POST data screen

### ISSUE THREAD

**Issue by andyboeh** [privacyidea/simplesamlphp-module-privacyidea#11]
After successful login, a print_r array of user attributes is displayed for a short period of time in the browser window. This is due to missing "TRUE" parameters in the call to print_r in privacyidea.php: [249](/privacyidea/simplesamlphp-module-privacyidea/blob/master/lib/Auth/Source/privacyidea.php#L249) and [256](/privacyidea/simplesamlphp-module-privacyidea/blob/master/lib/Auth/Source/privacyidea.php#L256)

**Comment by cornelinux** [comment]
THanks a lot for pointing this out.
Would you even be willing to issue a pull request?
