### ISSUE TITLE
Add SSO to authprocfilter

### ISSUE THREAD

**Issue by Great-Antique** [privacyidea/simplesamlphp-module-privacyidea#119]
Hello.

We want to be able to use SimpleSAMLphp as SSO with 2FA. We use this module to provide 2FA and we configure it as auth proc filter. Currently auth proc filter doesn't support SSO and users have to provide second factor for each new SP.

This case has been already described in #95 (PR #106) and even implemented but due to security issue it was removed in #109 (PR #110).

SSO (in auth proc filter) is still needed for us so we want to help you to implement it. So the question is what can we do for you?

One of the ways to implement it is to repeat #106 but with another state's field because `Expire` is set by SimpleSAMLphp after auth source login. Maybe you can propose another way.

We understand that this is wanted by us so we can help you with implementation and/or testing.

**Comment by nilsbehlen** [comment]
Hi,
im not very vell versed with this module, but after reading the things you linked, i think https://github.com/privacyidea/simplesamlphp-module-privacyidea/issues/95#issuecomment-756073325 is the way to go.
However, looking at the [base class](https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Auth/ProcessingFilter.php), there is no way to be notifed about the logout in a authproc scenario.
In general, we need a way to persist information from one login to another but that information also has to be cleared on logout (which is something the authproc filter can't do itself, so saml has to do it).

In #109 the faulty behavior is observed in an authsource scenario, did you try to reproduce this with authproc?

**Comment by Great-Antique** [comment]
Hi,

we have implemented SSO in our repository. See commit https://github.com/uvoteam/simplesamlphp-module-privacyidea/commit/4b34647fa2e82c663995db21ef91d1522be6383e

But there are some things that might not fit your needs:
1. Our changes are based on version 1.9. Becase we haven't updated to 2.0 yet.
2. Our implementation does not support several IdP with enabled and configured privacyidea module (as auth proc filter) because SimpleSAMLphp's session does not pass any arguments to logout handler (which we register to clean up data for SSO). See https://github.com/uvoteam/simplesamlphp-module-privacyidea/blob/1.9/lib/Auth/Process/privacyidea.php#L170-L178
3. Our implementation supports only "auth proc filter" method of configuration.

In the future we definitely update module to version 2.0+ and upgrade our SSO implementation.

So I think we can close this issue for now.

But if you know what should we change to fit your needs and to be merged into this repo - please let me know so we can do it. It would be great to be merged!

**Comment by lukasmatusiewicz** [comment]
Hi @Great-Antique, 

Thank you for your work and suggestions! 
I've implemented your SSO to 2.0 to test it and I become this fatal error on the second try to log in (in SP):

`Fatal error: Cannot declare class SimpleSAML_Session, because the name is already in use in /usr/share/simplesamlphp/lib/SimpleSAML/Session.php on line 19`

Did you have this error already?

**Comment by Great-Antique** [comment]
@lukasmatusiewicz 

Hi,

no, we use our implementation in production for last month and we didn't see any errors. But our implementation is based on 1.9.*. We use only `\SimpleSAML\Session` (in our changes) so I don't know why such errors may be occurred.

Currently we don't have time/resources to upgrade your module to 2.0.

At first glance it looks like SimpleSAMLphp's autoload is not working right or `SimpleSAML_Session` class declared twice for some reasons. Could you make PR (maybe marked as WIP) with these changes?

**Comment by lukasmatusiewicz** [comment]
#133
