### ISSUE TITLE
upgrade issue from 1.9 to 2.0

### ISSUE THREAD

**Issue by barrydegraaff** [privacyidea/simplesamlphp-module-privacyidea#123]
When I try to upgrade to 2.0 version of this module I see the following error:

      SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
      
      Backtrace:
      1 www/_include.php:17 (SimpleSAML_exception_handler)
      0 [builtin] (N/A)
      Caused by: Exception: Could not resolve 'privacyidea:privacyidea': no class named 'SimpleSAML\Module\privacyidea\Auth\Source\privacyidea' or 'sspmod_privacyidea_Auth_Source_privacyidea'.
      Backtrace:
      5 lib/SimpleSAML/Module.php:457 (SimpleSAML\Module::resolveClass)
      4 lib/SimpleSAML/Auth/Source.php:335 (SimpleSAML\Auth\Source::parseAuthSource)
      3 lib/SimpleSAML/Auth/Source.php:381 (SimpleSAML\Auth\Source::getById)
      2 lib/SimpleSAML/IdP.php:105 (SimpleSAML\IdP::__construct)
      1 lib/SimpleSAML/IdP.php:139 (SimpleSAML\IdP::getById)
      0 www/saml2/idp/SSOService.php:23 (N/A)

Probably a dependency issue, this happens when I upgrade by using the sources from this repo. At this time I have a different issue with using composer, that fails on a different dependancy.

        Problem 1
          - phpunit/phpunit[7.5.0, ..., 7.5.20] require php ^7.1 -> your php version (8.0.14) does not satisfy that requirement.
          - Root composer.json requires phpunit/phpunit ^7.5 -> satisfiable by phpunit/phpunit[7.5.0, ..., 7.5.20].
      

Any tips on how to fix the first issue? it would be much appreciated!

**Comment by nilsbehlen** [comment]
Hi,
you need to update your config aswell, take a look [here](https://github.com/privacyidea/simplesamlphp-module-privacyidea/blob/master/docs/privacyidea.md#method-1-authsource)

**Comment by barrydegraaff** [comment]
Thanks, I will try it out and close this issue in the meantime

**Comment by barrydegraaff** [comment]
I retried on a fresh installation of simplesamlphp and installed via Composer version 2.0 of this plugin, no matter how I configure the authsource, I cannot authenticate using version 2.0. Again I have no issues setting this up with version 1.9.

I am using an SQL table (wordpress template) to store the usernames and passwords and set TOTP token in privacyidea.

Depending on if I enable doTriggerChallenge and doSendPassword, I see a different error but it never works. Also it seems 2.0 always asks for an OTP even if the user does not have a token and I set a policy to allow it (for testing)


      [2021-12-29 08:00:51,308][945][140521665361728][INFO][privacyidea.lib.resolvers.SQLIdResolver:558] using the connect string mysql+pymysql://pi:***@localhost/pi_auth
      [2021-12-29 08:00:51,325][945][140521665361728][INFO][privacyidea.lib.user:236] user 'barry' found in resolver 'pi'
      [2021-12-29 08:00:51,325][945][140521665361728][INFO][privacyidea.lib.user:238] userid resolved to '10' 
      [2021-12-29 08:00:51,360][945][140521665361728][INFO][privacyidea.lib.user:404] User 'barry' from realm 'barrydegraaff.tk' tries to authenticate
      [2021-12-29 08:00:51,361][945][140521665361728][INFO][privacyidea.lib.user:416] user User(login='barry', realm='barrydegraaff.tk', resolver='pi') failed to authenticate.
      [2021-12-29 08:01:20,488][945][140521665361728][INFO][privacyidea.lib.resolvers.SQLIdResolver:558] using the connect string mysql+pymysql://pi:***@localhost/pi_auth
      [2021-12-29 08:01:20,502][945][140521665361728][INFO][privacyidea.lib.user:236] user 'barry' found in resolver 'pi'
      [2021-12-29 08:01:20,502][945][140521665361728][INFO][privacyidea.lib.user:238] userid resolved to '10' 
      [2021-12-29 08:01:20,537][945][140521665361728][INFO][privacyidea.lib.user:404] User 'barry' from realm 'barrydegraaff.tk' tries to authenticate
      [2021-12-29 08:01:20,538][945][140521665361728][INFO][privacyidea.lib.user:416] user User(login='barry', realm='barrydegraaff.tk', resolver='pi') failed to authenticate.
      
      
      [2021-12-29 08:08:18,446][945][140521665361728][INFO][privacyidea.lib.resolvers.SQLIdResolver:558] using the connect string mysql+pymysql://pi:***@localhost/pi_auth
      [2021-12-29 08:08:18,460][945][140521665361728][INFO][privacyidea.lib.user:236] user 'barry' found in resolver 'pi'
      [2021-12-29 08:08:18,460][945][140521665361728][INFO][privacyidea.lib.user:238] userid resolved to '10' 
      [2021-12-29 08:08:18,489][945][140521665361728][INFO][privacyidea.api.lib.postpolicy:471] There is no machine with IP=IPAddress('127.0.0.1')
      [2021-12-29 08:08:54,442][945][140521665361728][INFO][privacyidea.lib.resolvers.SQLIdResolver:558] using the connect string mysql+pymysql://pi:***@localhost/pi_auth
      [2021-12-29 08:08:54,455][945][140521665361728][INFO][privacyidea.lib.user:236] user 'barry' found in resolver 'pi'
      [2021-12-29 08:08:54,456][945][140521665361728][INFO][privacyidea.lib.user:238] userid resolved to '10' 
      [2021-12-29 08:08:54,485][945][140521665361728][INFO][privacyidea.api.lib.postpolicy:471] There is no machine with IP=IPAddress('127.0.0.1')
      

![Screenshot from 2021-12-29 09-14-24](https://user-images.githubusercontent.com/4353213/147641436-bc7eeb79-b298-48ad-987d-6f8ee66d6fa1.png)
![Screenshot from 2021-12-29 09-14-02](https://user-images.githubusercontent.com/4353213/147641438-3427ab90-9804-4a9f-bf9c-cabed7a6e77f.png)
![Screenshot from 2021-12-29 09-11-21](https://user-images.githubusercontent.com/4353213/147641439-4e71f9cc-6c0b-47d1-879e-2e9919dc6051.png)
![Screenshot from 2021-12-29 09-11-05](https://user-images.githubusercontent.com/4353213/147641440-9d5d246f-3491-467d-9c29-8585ec82d86b.png)
![Screenshot from 2021-12-29 09-10-47](https://user-images.githubusercontent.com/4353213/147641441-b166ae8b-9e81-4490-b86f-afef8aaffcce.png)


Any clues on what I am missing? Thanks!

**Comment by barrydegraaff** [comment]
In addition it seems like setting a service account and password is now required, at least I am served an error if I do not set it.

**Comment by lukasmatusiewicz** [comment]
You can set `doTriggerChallenge` or `doSendPassword` (it should be a string, not bool), not both at the same time. 
`doSendPassword` means that the user should give a token and its PIN set in privacyIDEA. It asks you for a pin first and then for OTP. 
`doTriggerChallenge` trigger all users tokens and the PIN doesn't matter anymore. To process `doTriggerChallenge` privacyIDEA need to know your `serviceAccount` and `servicePass`.

Please check if those things are correct in your setup.

**Comment by barrydegraaff** [comment]
After I fill the OTP field, I again see the screen with the OTP field, no error on the screen. I see in the logs:

      [2021-12-30 10:13:12,181][918][140028427745088][INFO][privacyidea.lib.resolvers.SQLIdResolver:558] using the connect string mysql+pymysql://pi:***@localhost/pi_auth
      [2021-12-30 10:13:12,636][918][140028427745088][INFO][privacyidea.api.auth:289] Local admin 'admin' successfully logged in.
      [2021-12-30 10:13:12,720][918][140028427745088][INFO][privacyidea.lib.resolvers.SQLIdResolver:558] using the connect string mysql+pymysql://pi:***@localhost/pi_auth
      [2021-12-30 10:13:12,738][918][140028427745088][INFO][privacyidea.lib.user:236] user 'barry' found in resolver 'pi'
      [2021-12-30 10:13:12,740][918][140028427745088][INFO][privacyidea.lib.user:238] userid resolved to '10' 
      [2021-12-30 10:13:19,819][918][140028427745088][INFO][privacyidea.lib.resolvers.SQLIdResolver:558] using the connect string mysql+pymysql://pi:***@localhost/pi_auth
      [2021-12-30 10:13:19,838][918][140028427745088][INFO][privacyidea.lib.user:236] user 'barry' found in resolver 'pi'
      [2021-12-30 10:13:19,838][918][140028427745088][INFO][privacyidea.lib.user:238] userid resolved to '10' 
      [2021-12-30 10:13:19,957][918][140028427745088][INFO][privacyidea.api.lib.postpolicy:471] There is no machine with IP=IPAddress('127.0.0.1')

The token fail counter is not incremented, so it seems PI does not see this as a failed login.... so I was thinking maybe a php session issue, moved to memcache, makes no difference.

Attached the config fles, it does not matter if I use the test configured authentication sources or try a real log-in, the effect is, I see the OTP screen over and over again.

[authsources.php.zip](https://github.com/privacyidea/simplesamlphp-module-privacyidea/files/7792504/authsources.php.zip)

In SimpleSAMLPHP it logs:

      Dec 30 10:21:44 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'sspmod_core_Auth_UserPassBase' is now using namespaces, please use 'SimpleSAML\Module\core\Auth\UserPassBase' instead.
      Dec 30 10:21:44 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
      Dec 30 10:21:44 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Auth_State' is now using namespaces, please use 'SimpleSAML\Auth\State'.
      Dec 30 10:21:44 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Module' is now using namespaces, please use 'SimpleSAML\Module'.
      Dec 30 10:21:44 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Utilities' is now using namespaces, please use 'SimpleSAML\Utilities'.
      Dec 30 10:21:44 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
      Dec 30 10:21:44 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Auth_State' is now using namespaces, please use 'SimpleSAML\Auth\State'.
      Dec 30 10:21:44 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Configuration' is now using namespaces, please use 'SimpleSAML\Configuration'.
      Dec 30 10:21:44 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_XHTML_Template' is now using namespaces, please use 'SimpleSAML\XHTML\Template'.
      Dec 30 10:21:44 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'sspmod_core_Auth_UserPassBase' is now using namespaces, please use 'SimpleSAML\Module\core\Auth\UserPassBase' instead.
      Dec 30 10:21:44 simplesamlphp ERROR [4c2ad9ffcc] SimpleSAML\Error\Exception: Error 8 - Undefined index: AuthId at /etc/simplesamlphp/lib/SimpleSAML/Auth/Source.php:49
      Dec 30 10:21:44 simplesamlphp ERROR [4c2ad9ffcc] Backtrace:
      Dec 30 10:21:44 simplesamlphp ERROR [4c2ad9ffcc] 6 /etc/simplesamlphp/www/_include.php:44 (SimpleSAML_error_handler)
      Dec 30 10:21:44 simplesamlphp ERROR [4c2ad9ffcc] 5 /etc/simplesamlphp/lib/SimpleSAML/Auth/Source.php:49 (SimpleSAML\Auth\Source::__construct)
      Dec 30 10:21:44 simplesamlphp ERROR [4c2ad9ffcc] 4 /etc/simplesamlphp/modules/core/lib/Auth/UserPassBase.php:112 (SimpleSAML\Module\core\Auth\UserPassBase::__construct)
      Dec 30 10:21:44 simplesamlphp ERROR [4c2ad9ffcc] 3 /etc/simplesamlphp/modules/privacyidea/lib/Auth/Source/PrivacyideaAuthSource.php:59 (sspmod_privacyidea_Auth_Source_PrivacyideaAuthSource::__construct)
      Dec 30 10:21:44 simplesamlphp ERROR [4c2ad9ffcc] 2 /etc/simplesamlphp/modules/privacyidea/www/formbuilder.php:135 (require)
      Dec 30 10:21:44 simplesamlphp ERROR [4c2ad9ffcc] 1 /etc/simplesamlphp/lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
      Dec 30 10:21:44 simplesamlphp ERROR [4c2ad9ffcc] 0 /etc/simplesamlphp/www/module.php:10 (N/A)
      Dec 30 10:21:44 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Auth_Source' is now using namespaces, please use 'SimpleSAML\Auth\Source'.
      Dec 30 10:21:44 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Module' is now using namespaces, please use 'SimpleSAML\Module'.
      Dec 30 10:22:04 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
      Dec 30 10:22:04 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Auth_State' is now using namespaces, please use 'SimpleSAML\Auth\State'.
      Dec 30 10:22:04 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Auth_Source' is now using namespaces, please use 'SimpleSAML\Auth\Source'.
      Dec 30 10:22:04 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'sspmod_core_Auth_UserPassBase' is now using namespaces, please use 'SimpleSAML\Module\core\Auth\UserPassBase' instead.
      Dec 30 10:22:04 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Module' is now using namespaces, please use 'SimpleSAML\Module'.
      Dec 30 10:22:04 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Utilities' is now using namespaces, please use 'SimpleSAML\Utilities'.
      Dec 30 10:22:04 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
      Dec 30 10:22:04 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Auth_State' is now using namespaces, please use 'SimpleSAML\Auth\State'.
      Dec 30 10:22:04 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Configuration' is now using namespaces, please use 'SimpleSAML\Configuration'.
      Dec 30 10:22:04 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_XHTML_Template' is now using namespaces, please use 'SimpleSAML\XHTML\Template'.
      Dec 30 10:22:04 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'sspmod_core_Auth_UserPassBase' is now using namespaces, please use 'SimpleSAML\Module\core\Auth\UserPassBase' instead.
      Dec 30 10:22:04 simplesamlphp ERROR [4c2ad9ffcc] SimpleSAML\Error\Exception: Error 8 - Undefined index: AuthId at /etc/simplesamlphp/lib/SimpleSAML/Auth/Source.php:49
      Dec 30 10:22:04 simplesamlphp ERROR [4c2ad9ffcc] Backtrace:
      Dec 30 10:22:04 simplesamlphp ERROR [4c2ad9ffcc] 6 /etc/simplesamlphp/www/_include.php:44 (SimpleSAML_error_handler)
      Dec 30 10:22:04 simplesamlphp ERROR [4c2ad9ffcc] 5 /etc/simplesamlphp/lib/SimpleSAML/Auth/Source.php:49 (SimpleSAML\Auth\Source::__construct)
      Dec 30 10:22:04 simplesamlphp ERROR [4c2ad9ffcc] 4 /etc/simplesamlphp/modules/core/lib/Auth/UserPassBase.php:112 (SimpleSAML\Module\core\Auth\UserPassBase::__construct)
      Dec 30 10:22:04 simplesamlphp ERROR [4c2ad9ffcc] 3 /etc/simplesamlphp/modules/privacyidea/lib/Auth/Source/PrivacyideaAuthSource.php:59 (sspmod_privacyidea_Auth_Source_PrivacyideaAuthSource::__construct)
      Dec 30 10:22:04 simplesamlphp ERROR [4c2ad9ffcc] 2 /etc/simplesamlphp/modules/privacyidea/www/formbuilder.php:135 (require)
      Dec 30 10:22:04 simplesamlphp ERROR [4c2ad9ffcc] 1 /etc/simplesamlphp/lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
      Dec 30 10:22:04 simplesamlphp ERROR [4c2ad9ffcc] 0 /etc/simplesamlphp/www/module.php:10 (N/A)
      Dec 30 10:22:04 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Auth_Source' is now using namespaces, please use 'SimpleSAML\Auth\Source'.
      Dec 30 10:22:04 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Module' is now using namespaces, please use 'SimpleSAML\Module'.
      Dec 30 10:22:11 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
      Dec 30 10:22:11 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Auth_State' is now using namespaces, please use 'SimpleSAML\Auth\State'.
      Dec 30 10:22:11 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Auth_Source' is now using namespaces, please use 'SimpleSAML\Auth\Source'.
      Dec 30 10:22:11 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'sspmod_core_Auth_UserPassBase' is now using namespaces, please use 'SimpleSAML\Module\core\Auth\UserPassBase' instead.
      Dec 30 10:22:11 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Module' is now using namespaces, please use 'SimpleSAML\Module'.
      Dec 30 10:22:11 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Utilities' is now using namespaces, please use 'SimpleSAML\Utilities'.
      Dec 30 10:22:11 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
      Dec 30 10:22:11 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Auth_State' is now using namespaces, please use 'SimpleSAML\Auth\State'.
      Dec 30 10:22:11 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Configuration' is now using namespaces, please use 'SimpleSAML\Configuration'.
      Dec 30 10:22:11 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_XHTML_Template' is now using namespaces, please use 'SimpleSAML\XHTML\Template'.
      Dec 30 10:22:11 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'sspmod_core_Auth_UserPassBase' is now using namespaces, please use 'SimpleSAML\Module\core\Auth\UserPassBase' instead.
      Dec 30 10:22:11 simplesamlphp ERROR [4c2ad9ffcc] SimpleSAML\Error\Exception: Error 8 - Undefined index: AuthId at /etc/simplesamlphp/lib/SimpleSAML/Auth/Source.php:49
      Dec 30 10:22:11 simplesamlphp ERROR [4c2ad9ffcc] Backtrace:
      Dec 30 10:22:11 simplesamlphp ERROR [4c2ad9ffcc] 6 /etc/simplesamlphp/www/_include.php:44 (SimpleSAML_error_handler)
      Dec 30 10:22:11 simplesamlphp ERROR [4c2ad9ffcc] 5 /etc/simplesamlphp/lib/SimpleSAML/Auth/Source.php:49 (SimpleSAML\Auth\Source::__construct)
      Dec 30 10:22:11 simplesamlphp ERROR [4c2ad9ffcc] 4 /etc/simplesamlphp/modules/core/lib/Auth/UserPassBase.php:112 (SimpleSAML\Module\core\Auth\UserPassBase::__construct)
      Dec 30 10:22:11 simplesamlphp ERROR [4c2ad9ffcc] 3 /etc/simplesamlphp/modules/privacyidea/lib/Auth/Source/PrivacyideaAuthSource.php:59 (sspmod_privacyidea_Auth_Source_PrivacyideaAuthSource::__construct)
      Dec 30 10:22:11 simplesamlphp ERROR [4c2ad9ffcc] 2 /etc/simplesamlphp/modules/privacyidea/www/formbuilder.php:135 (require)
      Dec 30 10:22:11 simplesamlphp ERROR [4c2ad9ffcc] 1 /etc/simplesamlphp/lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
      Dec 30 10:22:11 simplesamlphp ERROR [4c2ad9ffcc] 0 /etc/simplesamlphp/www/module.php:10 (N/A)
      Dec 30 10:22:11 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Auth_Source' is now using namespaces, please use 'SimpleSAML\Auth\Source'.
      Dec 30 10:22:11 simplesamlphp WARNING [4c2ad9ffcc] The class or interface 'SimpleSAML_Module' is now using namespaces, please use 'SimpleSAML\Module'.

**Comment by lukasmatusiewicz** [comment]
Also, we recommend you turn on the debug because your log shows only errors. Then you can see what request you send (and maybe what parameters are missing) and also what an answer you become from PI.

**Comment by barrydegraaff** [comment]
@lukasmatusiewicz attached the logs when set to DEBUG loglevel. I have run 3 tests. Doing curl directly to the /validate/check just works, this proves that the username/password/otp/dns is working.

Then I tested with  'doTriggerChallenge' => 'false',  'doSendPassword' => 'true', and 'doTriggerChallenge' => 'true',  'doSendPassword' => 'false' see the attached log.

In the mean time I wrote a drop-in replacement module that works as well as a replacement for the simplesamlphp-module-privacyidea, it is a single file with 36 lines of code.... and it does not require Composer et all.....

      <?php
      
      declare(strict_types=1);
      
      namespace SimpleSAML\Module\barrypi\Auth\Source;
      
      use SimpleSAML\Error;
      use SimpleSAML\Utils;
      
      class MyAuth extends \SimpleSAML\Module\core\Auth\UserPassBase
      {
         protected function login($username, $password) {
            $ch = curl_init();
            
            curl_setopt($ch, CURLOPT_URL,"http://localhost:8000/validate/samlcheck");
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query(array('user' => $username, 'pass' => $password)));
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            $server_output = curl_exec($ch);
            curl_close ($ch);
            $privacyIdea = json_decode($server_output, TRUE);
            if ($privacyIdea['result']['status'] && $privacyIdea['result']['value']['auth']) {
               return [
                  'samlLoginName' => [$privacyIdea['result']['value']['attributes']['username']],
                  'givenName' => [$privacyIdea['result']['value']['attributes']['givenname']],
                  'emailAddress' => [$privacyIdea['result']['value']['attributes']['email']],
                  'telePhone' => [$privacyIdea['result']['value']['attributes']['phone']],
                  'fullName' => [$privacyIdea['result']['value']['attributes']['givenname']],
               ];
            }
            else
            {
               throw new \SimpleSAML\Error\Error('WRONGUSERPASS');
            }
         }
      }

**Comment by lukasmatusiewicz** [comment]
I read your configs and i see some issues:

In attached config file is: `'logging.level' => SimpleSAML\Logger::NOTICE`. Should be DEBUG.
Hope you have changed that.

In saml20.idp.hosted.php is:
`$metadata['__DYNAMIC:1__'] = [`
my array with idp config is called:
`$idp_config = array(`

Your array in authsources.php is:
`'privacyidea' => array(`
And should be:
`$config['privacyidea'] = array(`

Other settings looks good, please try to fix this 2 lines and let me know.
