### ISSUE TITLE
Only first WebAuthn token is usable

### ISSUE THREAD

**Issue by melanger** [privacyidea/simplesamlphp-module-privacyidea#127]
When a user has multiple WebAuthn tokens (devices) registered, only the first one can be actually used (with doTriggerChallenge).

This is because only the first challenge is used (see https://github.com/privacyidea/sdk-php/blob/f3f1505a725bd85547ff50d467602bbbeadaf871/src/PIResponse.php#L185), which restricts the authentication to a single authenticator ID.

**Comment by lukasmatusiewicz** [comment]
Closed by 2f0173a
