### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by eheydrick** [privacyidea/simplesamlphp-module-privacyidea#15]
Could you release a new version? I'm interested in https://github.com/privacyidea/simplesamlphp-module-privacyidea/commit/1b9dd8c66e4a9d02fc1f47a56d2287c047aaf821 and https://github.com/privacyidea/simplesamlphp-module-privacyidea/commit/765d7153b7ee7ad7132f0887ae23b0abd0ca9813. Thanks!

**Comment by cornelinux** [comment]
You mean like to the packagist?

**Comment by eheydrick** [comment]
Yes.

**Comment by cornelinux** [comment]
OK.

**Comment by eheydrick** [comment]
Thanks!
