### ISSUE TITLE
otpextra option gone

### ISSUE THREAD

**Issue by AdamVB** [privacyidea/simplesamlphp-module-privacyidea#152]
With 1.9 we had the ```otpextra``` option, to have PIN and OTP in seperate forms like so:

![image](https://user-images.githubusercontent.com/15871966/167582575-070b8d20-9632-4f4e-b787-be2cdbbcc626.png)

Beginning from 2.0 this option is gone, can we add this back in to keep the user experience coherent?

**Comment by nilsbehlen** [comment]
Hi, we will keep this in mind for the next version.
