### ISSUE TITLE
Error 8 - Undefined index: pushAvailable

### ISSUE THREAD

**Issue by malavolti** [privacyidea/simplesamlphp-module-privacyidea#154]
On my log I see:

SimpleSAML\Error\Exception: Error 8 - Undefined index: pushAvailable at /var/simplesamlphp/vendor/simplesamlphp/simplesamlphp/modules/privacyidea/templates/LoginForm.php:300
Backtrace:
5 /var/simplesamlphp/vendor/simplesamlphp/simplesamlphp/www/_include.php:44 (SimpleSAML_error_handler)
4 /var/simplesamlphp/vendor/simplesamlphp/simplesamlphp/modules/privacyidea/templates/LoginForm.php:300 (require)
3 /var/simplesamlphp/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:560 (SimpleSAML\XHTML\Template::show)
2 /var/simplesamlphp/vendor/simplesamlphp/simplesamlphp/modules/privacyidea/www/FormBuilder.php:130 (require)
1 /var/simplesamlphp/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 /var/simplesamlphp/vendor/simplesamlphp/simplesamlphp/www/module.php:10 (N/A)

Is there a way to fix it?

on "templates/LoginForm.php" I read:

`<!-- Undefined index is suppressed and the default is used for these values -->`

Thank you so much!
Marco

**Comment by nilsbehlen** [comment]
Hi,
what is your configuration?
you can edit the line 300 of ` /var/simplesamlphp/vendor/simplesamlphp/simplesamlphp/modules/privacyidea/templates/LoginForm.php` to `!@$this->data['pushAvailable']` to suppress the "error".

**Comment by nilsbehlen** [comment]
we will include a proper fix for this in the next official version.
