### ISSUE TITLE
authsource not working correctly

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/simplesamlphp-module-privacyidea#164]
When configuring the plugin as `authsource` a couple of things look wierd.

"Authsource" in simpleSAMLphp means, that this plugin is the only/main source of authentication. Thus all authentication needs to run against privacyIDEA.

### password

The plugin display a login mask with fields "username" and "password". But this password-field has no effect.
The contents of this password-field (credentials) is supposed to be verified by privacyIDEA. Thus it needs to be sent to the privacyIDEA server. If there is a pin+otp, a password+otp or only otp or whatever is determined by the policies in the privacyIDEA server.

###  otpExtra

In 2017 the meaning of otpExtra was the following:

Normal behaviour:

he login mask has a username field and a password field.  password-field gets sent to privacyIDEA.

otpExrta activated:

the login mask has a username field, a password field and an OTP field. This has not technical background it is only a UI look-and-feel for users to get a specific understanding.
The contents from `password-field + otp-field` get sent to privacyIDEA. The same stuff as if the user would enter pin+otp in one field. It is only splitting the one field in two - nothing else. And this makes phsycological sense and is important.

# Implementation

## Existing Configuration of authproc filter

* doSendPassword (sends password from first authsource)
* ~~doSemdEmptyPass (not sure)~~
* doTriggerChallenge (sends a trigger challenge before displaying the input field)

## Sensible Config options for authsource

* authSourceMode: "SendPassword", "TriggerChallenge", "OtpExtra" (similar to SendPassword), "DoValidateCheckRequestWithEmptyPassword"
   * SendPassword (Default): UI has username + 1stPassword is sent via /validate/check  **2 fields**
   * TriggerChallenge: UI only displays username and /validate/triggerchallenge is sent **1 field**
   * OtpExtra: List SendPassword, but the field 1stPassword + OTP is concatenated **3 fields**
   * ~~DoValidage....": UI has only username and an empty password is sent via /validate/check **1 field**~~

* otpExtra is removed since it is contained in mode "OtpExtra".
* PasswordHint: already exists. 

If the mode has a typo or does not exist, we default to "SendPassword" and an error should be logged  (at least in the log file)

## New:

- Instead of `authsourceMode` will be used the name: `authenticationFlow`.

- To maintain uniformity, `authenticationFlow` will also be implemented into the `authproc`.

**Comment by lukasmatusiewicz** [comment]
todo:

- [ ]  Implement the authsource modes.

- [ ]  Update the config template with an `authSourceMode` option (Valid values: `sendPass`, `triggerChallenge`, and `otpExtra`).

- [ ]  Remove the following options from the config template: `doTriggerChallenge`, `doSendPassword`, `otpExtra`.

- [ ]  If the `authSourceMode` won't be found or the value will be invalid, process the authentication in the default mode and write a proper error to the log file.

**Comment by lukasmatusiewicz** [comment]
To authentication flow in authproc topic:

The logic in authproc differs from authsource. The default option is just to not process any of the other flows. Normally this is not bad, but `authenticationFlow` is "required" in settings even if it isn't in code. Maybe we should call it here: `changeFlow` or `undefaultFlow`?

I don't think, that we should change the code to fit the new definition...
@nilsbehlen ?

**Comment by nilsbehlen** [comment]
Why is it required to be in config file? we have to be able to handle a missing or empty entry there and set a default for `authenticationFlow` in the code, which would be do to nothing. This means just show the otp field for authproc or just show the username+password field for authsource. The "nothing" should also be a named option for `authenticationFlow` like `None` or `Default`.
