### ISSUE TITLE
Build a new template using Twig

### ISSUE THREAD

**Issue by malavolti** [privacyidea/simplesamlphp-module-privacyidea#169]
Hi,

From the version 1.15, SimpleSAMLphp allow to use Twig (https://twig.symfony.com/) templates to display web pages to users.

https://simplesamlphp.org/docs/stable/simplesamlphp-theming.html

Did someone create the twig template for SSP already?

Thank you so much!

**Comment by lukasmatusiewicz** [comment]
Hi @malavolti ,

I have no information if somebody has created such a template for now. But we invite you to research our community forum or open a new topic with this question there.

Here is the link: https://community.privacyidea.org/

Greets!

**Comment by lukasmatusiewicz** [comment]
The actual template method will be removed in simpleSAML v2.0

**Comment by malavolti** [comment]
https://simplesamlphp.org/docs/devel/simplesamlphp-changelog

**Version 2.0.0**

* Old-style PHP templates were removed
* Old-style dictionaries were removed

**Comment by malavolti** [comment]
On the 24th of February 2023 has been released the new major version of SimpleSAMLphp: v2.0.0:

https://simplesamlphp.org/docs/stable/simplesamlphp-upgrade-notes-2.0.html

Any news about the template?

Thank you so much!

**Comment by malavolti** [comment]
https://simplesamlphp.org/docs/1.19/simplesamlphp-changelog.html#final-release

This is the last release in the 1.19.x version branch. Extended security support ends today!

https://simplesamlphp.org/security/

Can you tell me how can I get help on this, please?

**Comment by lukasmatusiewicz** [comment]
We are working on the upgrade. I'll share any info about it here on GitHub.
Greets

**Comment by lukasmatusiewicz** [comment]
closed by #209
