### ISSUE TITLE
After update, <em> in login text is displayed

### ISSUE THREAD

**Issue by andyboeh** [privacyidea/simplesamlphp-module-privacyidea#17]
After a recent update, the login text now includes `<em>` as well as `</em>`. This is probably due to the addition of `htmlspecialchars` in one of the recent commits.

Should the translations/texts be changed to omit any HTML?

**Comment by eheydrick** [comment]
I think this can be closed. The extra `<em>`'s were removed in https://github.com/privacyidea/simplesamlphp-module-privacyidea/commit/52fc945181d7ea6ff61f893828f7bbcec202d54c and released in 1.5.1.

**Comment by cornelinux** [comment]
Thanks for the heads up!
