### ISSUE TITLE
PHP Error when accessing simplesamlphp web page

### ISSUE THREAD

**Issue by gabardyne** [privacyidea/simplesamlphp-module-privacyidea#192]
Hello,

I've installed the plugin with composer 2.5.5.

I launched the command composer require privacyidea/simplesamlphp-module-privacyidea in my simplesamlphp rootdir (/var/simplesamlphp).

I'm using php 8.2, and my OS is CentOS 7.

I've this error when I try to access to simplesamlphp web page:

PHP Fatal error:  Uncaught Error: Failed opening required '/var/simplesamlphp/vendor/composer/../../tests/_autoload_modules.php' (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /var/simplesamlphp/vendor/composer/autoload_real.php:41\nStack trace:\n#0 /var/simplesamlphp/vendor/composer/autoload_real.php(45): {closure}()\n#1 /var/simplesamlphp/vendor/autoload.php(25): ComposerAutoloaderInit03590d0c044a5d25ee9291b3dc5654e6::getLoader()\n#2 /var/simplesamlphp/src/_autoload.php(14): require_once('...')\n#3 /var/simplesamlphp/public/_include.php(6): require_once('...')\n#4 /var/simplesamlphp/public/index.php(7): require_once('...')\n#5 {main}\n  thrown in /var/simplesamlphp/vendor/composer/autoload_real.php on line 41

What am I missing here?

Regards,

Gab

**Comment by lukasmatusiewicz** [comment]
Hi @gabardyne, which simplesamlphp (core) version have you installed?

**Comment by lukasmatusiewicz** [comment]
https://github.com/privacyidea/simplesamlphp-module-privacyidea#readme

**Comment by lukasmatusiewicz** [comment]
v2.0 forces a lot of changes. For now, our module is not compatible with it, but we are working on it.

Regards,
luc
