### ISSUE TITLE
triggerChallenge and Email Token

### ISSUE THREAD

**Issue by malavolti** [privacyidea/simplesamlphp-module-privacyidea#194]
Hi to all of you,

I've noticed that if I set the "triggerChallenge" authentication flow and I configure the Email Token for my user, every time I perform a login on my IdP, I get an OTP by email without asking.
I have set up the Email Token & the TOTP Token for my user, but I think that receiving the OTP via email each time I perform a login is not the correct behaviour. I expect to be able to decide if I want to use an Application to generate the OTP code or, instead, send the OTP code via e-mail. Right?

Is this the normal behaviour?

**Comment by nilsbehlen** [comment]
Hello, this is the normal behavior. As the name suggests, all possible challenges for the authenticating user (email) will be triggered for every login. The other option to trigger the email is by entering the PIN in the OTP field.

**Comment by malavolti** [comment]
Thank you @nilsbehlen!
Is it possible to prevent this behaviour? I have added a specific button to allow user to request an OTP sent to his email. I can only use the "default" authenticationFlow to prevent it or there is another, and better, way?

I see that with "triggerChallange" the QR Code is not created if the user does not have it without enable the "doEnrollToken" flag. Is there a way to use the "triggerChallenge" authentication flow and create a new OTP token with a new QR code when an user make his first login?

Thank you so much!
Marco

**Comment by nilsbehlen** [comment]
Triggerchallenge and enrolltoken are independent. You can enable both which should result in users having no token getting one.
Please note that this is not the place to do consulting on the software
