### ISSUE TITLE
Support for SimpleSAMLphp 2.0 and newer PHP 8.x versions

### ISSUE THREAD

**Issue by vahem2lu** [privacyidea/simplesamlphp-module-privacyidea#196]
Hi
Is there going to be support for SSP>2 and PHP>=8?

**Comment by nilsbehlen** [comment]
Hi,
probably, but it will take some time because (iirc) there will be incompatible changes and we are currently not working on this project

**Comment by vahem2lu** [comment]
What's the latest supported PHP and SSP? As SSP 1.19.4 supports PHP8.0 is this also capable for this?

**Comment by nilsbehlen** [comment]
Last i know of is 1.19.3 with php7.4.

**Comment by vahem2lu** [comment]
https://simplesamlphp.org/docs/1.19/simplesamlphp-changelog.html
SimpleSAMLphp 1.19.8 and support for PHP 8.0 and PHP 8.1

**Comment by jsaathof** [comment]
According to tis page: https://www.php.net/supported-versions.php PHP 7.x went out of support in November 2022. Even PHP 8.0 only gets security updates.fixes.

**Comment by malavolti** [comment]
https://simplesamlphp.org/docs/1.19/simplesamlphp-changelog.html#final-release

This is the last release in the 1.19.x version branch. Extended security support ends today! 

https://simplesamlphp.org/security/

Can you tell me how can I get help on this, please?

**Comment by nilsbehlen** [comment]
@lukasmatusiewicz is currently working on upgrading this to the latest ssp

**Comment by jmohacsi** [comment]
Any progress on SSP2.x support? How can one help the porting?

**Comment by lukasmatusiewicz** [comment]
Hi @jmohacsi ,
The upgrade is mostly done. Now we are migrating the translations. It shouldn't take more than 2 weeks to end up the testing phase. Any further info comes here. We will be happy to receive some feedback if you'd like to test it soon.

**Comment by jmohacsi** [comment]
Excellent news. We are happy to test it.

**Comment by lukasmatusiewicz** [comment]
@jmohacsi ,
are you using this module as an authproc filter or authsource?
Greets

**Comment by jmohacsi** [comment]
We are using it as authproc filter.

**Comment by lukasmatusiewicz** [comment]
Ok. I've already tested it as authsource. Can you test this code as an authproc filter for me? Here is my email: lukas.matusiewicz@netknights.it
