### ISSUE TITLE
Save a device

### ISSUE THREAD

**Issue by vahem2lu** [privacyidea/simplesamlphp-module-privacyidea#197]
Using simplesamlphp module in `privacyidea:PrivacyideaAuthProc` mode. If a "new" device is being used to log in is there a possibility to "save a device" for example xxx days?
The default behaviour is that 2FA is being asked every time I sign in, which would not be convenient.

**Comment by nilsbehlen** [comment]
No there is not, if there was, it would be centrally managed in privacyidea.

> xxx days?
> The default behaviour is that 2FA is being asked every time I sign in, which would not be convenient.

I do not think this is something we want, especially in **days**. Additional security requires compromise in comfort.
