### ISSUE TITLE
simplesamlphp and u2f possible?

### ISSUE THREAD

**Issue by vDorst** [privacyidea/simplesamlphp-module-privacyidea#2]
Is it possible to login simplesamlphp icm u2f key?

**Comment by cornelinux** [comment]
The plugin does not replace the login screen of simpleSAMLphp. Thus this is not possible at the moment.

But technically it should be possible to implement.

If you have running privacyIDEA on https://yourIdP/privacyidea and the IdP is on the same machine and the login is on the same machine, you should be able to:

* enroll the U2F token with privacyIDEA and
* login at simpleSAMLphp

**Comment by cornelinux** [comment]
The commit https://github.com/privacyidea/simplesamlphp-module-privacyidea/commit/d637e40167c9a0dcb593114c5c603a887a784502 introduced its own Web UI, which now also supports challenge response.

For this to work, we will also need privacyIDEA 2.8.

Next working on U2F.
