### ISSUE TITLE
Inconsistent type in return

### ISSUE THREAD

**Issue by enricomv** [privacyidea/simplesamlphp-module-privacyidea#203]
In our setup we do have a list of SP entityID in the excludeEntityIDs and the 'SSO' defined as 'true' in the AuthProc configuration. 

When we login into one of excluded SP and then login into a SP that requires 2FA, the module raises the following   exception

```
Backtrace:
1 www/_include.php:20 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: TypeError: Return value of SimpleSAML\Module\privacyidea\Auth\Utils::checkForValidSSO() must be of the type boolean, null returned
Backtrace:
6 modules/privacyidea/lib/Auth/Utils.php:209 (SimpleSAML\Module\privacyidea\Auth\Utils::checkForValidSSO)
5 modules/privacyidea/lib/Auth/Process/PrivacyideaAuthProc.php:99 (SimpleSAML\Module\privacyidea\Auth\Process\PrivacyideaAuthProc::process)
4 lib/SimpleSAML/Auth/ProcessingChain.php:210 (SimpleSAML\Auth\ProcessingChain::processState)
3 lib/SimpleSAML/IdP.php:335 (SimpleSAML\IdP::postAuth)
2 lib/SimpleSAML/IdP.php:420 (SimpleSAML\IdP::handleAuthenticationRequest)
1 modules/saml/lib/IdP/SAML2.php:498 (SimpleSAML\Module\saml\IdP\SAML2::receiveAuthnRequest)
0 www/saml2/idp/SSOService.php:26 (N/A)

```

It seems that the function

https://github.com/privacyidea/simplesamlphp-module-privacyidea/blob/e7e2c12a9a871659a2208c4e4f1960e2a3a5ac3c/lib/Auth/Utils.php#L198

returns a null instead of false due to the line

https://github.com/privacyidea/simplesamlphp-module-privacyidea/blob/e7e2c12a9a871659a2208c4e4f1960e2a3a5ac3c/lib/Auth/Utils.php#L209

Thanks in advance for support

**Comment by nilsbehlen** [comment]
Hi, please check v3.1.2, that should fix it.

**Comment by enricomv** [comment]
It works! Thanks a lot for rapid fix
