### ISSUE TITLE
Concatenation in the mapping

### ISSUE THREAD

**Issue by eubyte** [privacyidea/simplesamlphp-module-privacyidea#23]
Is it possible to concatenate privacyIDEA fields for mapping to saml attributes? Something along these lines (see displayName):

    'attributemap' => array('username' => 'samlLoginName',
                           'surname' => 'surName',
                           'givenname' => 'givenName',
                           'givenname'.' '.surname' => 'displayName',
                           'email' => 'emailAddress',
                           'phone' => 'telePhone',
                           'mobile' => 'mobilePhone',
                           ),

Also, is there a support for 'core:AttributeMap' of simpleAmlPhp where one can specify mapping to multiple attributes. For example:

     'email' => array('email', 'emailAddress')

Thank you!

**Comment by cornelinux** [comment]
Both is not possible. 
You are welcome to explain in more detail, what you want to achieve, contribute an idea or PR.
