### ISSUE TITLE
SimpleSAML\Error\CannotSetCookie: Headers already sent.

### ISSUE THREAD

**Issue by KebinuChiousu** [privacyidea/simplesamlphp-module-privacyidea#24]
/usr/local/openresty/nginx/www-root/sso/simplesamlphp (1.15.0-rc1)
PHP Version >= 5.4. You run: 7.1.9
privacyIDEA 2.19.1

SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Backtrace:
1 www/_include.php:45 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: SimpleSAML\Error\CannotSetCookie: Headers already sent.
Backtrace:
6 lib/SimpleSAML/Utils/HTTP.php:1157 (SimpleSAML\Utils\HTTP::setCookie)
5 lib/SimpleSAML/Session.php:648 (SimpleSAML_Session::doLogin)
4 lib/SimpleSAML/Auth/Source.php:224 (SimpleSAML_Auth_Source::loginCompleted)
3 lib/SimpleSAML/Auth/Source.php:145 (SimpleSAML_Auth_Source::completeAuth)
2 modules/privacyidea/lib/Auth/Source/privacyidea.php:369 (sspmod_privacyidea_Auth_Source_privacyidea::handleLogin)
1 modules/privacyidea/www/loginform.php:102 (require)
0 www/module.php:135 (N/A)

**Comment by laclaro** [comment]
Thank you for the report. However, I think this is outdated now. I never occurred to me. I'm closing this.
