### ISSUE TITLE
Namespace warnings

### ISSUE THREAD

**Issue by eheydrick** [privacyidea/simplesamlphp-module-privacyidea#28]
Getting these warnings about namespaces after upgrading to simplesamlphp 1.15. These occur when the privacyidea login page loads.

```
Feb 27 23:12:08 ip-10-5-2-78 simplesamlphp[28534]: 4 [40822102d6] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Feb 27 23:12:08 ip-10-5-2-78 simplesamlphp[28534]: 4 [40822102d6] The class or interface 'SimpleSAML_Module' is now using namespaces, please use 'SimpleSAML\Module'.
```

**Comment by cornelinux** [comment]
There are still some installations with 1.14.
Especially UCS 4.2 uses 1.14 to my knowledge.

We will check and change this accordingly. Since the deprecation warning in 1.15 is a smaller problem than a probable error in 1.14.

**Comment by NuvandaPV** [comment]
UCS 4.2 will go out of extended support in April 2024. We should reconsder switching to namespaces then.

**Comment by lukasmatusiewicz** [comment]
Update: UCS 5 still does not allow to use namespaces here. Still waiting for the green light in the new version.
