### ISSUE TITLE
Add token type to attribute list

### ISSUE THREAD

**Issue by nomennesc-io** [privacyidea/simplesamlphp-module-privacyidea#32]
Adding the token type as returned by privacyid3a to the saml attributes allows service providers to define more granular access control. For instance, you could differentiate between users that did and did not use 2FA if passthru is enabled, or block spass, sms, and e-mail tokens for specific services that have high security needs.

**Comment by cornelinux** [comment]
@nomennesc-io thanks a lot for the pull request!
@Mipronimo lets discuss it togeather in person.

**Comment by cornelinux** [comment]
Hi @nomennesc-io ,
thanks a lot for your pull request and looking into this.
I am sorry for the late response. Let's get back to this!

I think the idea is basically a good one to be able to add this information to the SAML response.
But there are I think some aspects to take into account that would need to be reflected by the PR #33.

* Token-Attribute in user attributes: The tokentype of the token is a token attribute, not a user attribute. 
Is it OK to add token information into the user return attributes?

* The response tree ``$body->detail`` may sometimes not exist. There is a policy, that you can suppress these values in the response. So we would need to add some error handling around it. Please first check, if the detail branch exists!

    ~~~~php
    if array_key_exists("detail", $body) {
      $attributes['tokentype'] = array($body->detail->type);
    }
    ~~~~

* It might be a good idea, to also make the detail-information mappable. A response can e.g. have these detail-information:

    ~~~~json
    "detail": {
        "user": {},
        "threadid": 139965899175680,
        "message": "matching 1 tokens",
        "type": "spass",
        "serial": "PISP0012A8C4",
        "otplen": 6
    ~~~~
    In addition we might be interested in not only mapping the token*type* but maybe also the *serial* or the *otplen*
    Some tokens do not differ by the type, but by the serial: E.g. An enrolled yubikey and a smartphone app would both be *type=HOTP*, but the hardware token might be more reliable. The serial starts with an "UBOM", the smartphone with "OATH". So we might need a generic mapping of the details like such:
    
    ~~~~php
    /* the details get added to the user attributes */
    'detailmap' => array('serial' => 'samlSerialAttribute',
         			    'type' => 'samlTokenType),
    ~~~~

If you could incorporate this into your pull request, this would be great!
Thanks a lot
Cornelius

**Comment by cornelinux** [comment]
A fully blown detail could look like this:

~~~json
"detail": {
    "user-realm": "domain.fuzzi",
     "user": {
               "username": "kölbel",
               "givenname": "Cornelius",
               "surname": "Kölbel",
               "mobile": "+,+",
               "phone": "",
               "group": [
                              "CN=TOken USer,CN=Users,DC=testfoo,DC=intranet",
                              "CN=Domain Admins,CN=Users,DC=testfoo,DC=intranet"
                              ],
               "password": "",
               "email": "a@example.com; b@example.com"
         },
    "threadid": 140707867350784,
    "message": "matching 2 tokens",
    "type": "spass",
    "user-resolver": "domainfuzzi"
},
~~~~

So the detail map should be defined flexibly and only the keys, that are specified (above: "serial", "type") should be added to the attributes here https://github.com/privacyidea/simplesamlphp-module-privacyidea/blob/master/lib/Auth/Source/privacyidea.php#L297
after the "normal" user attributes have been processed.

**Comment by nomennesc-io** [comment]
Oh wow, that went fast all of a sudden, many thanks, you guys rock!
