### ISSUE TITLE
Support Auth Proc Filters

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/simplesamlphp-module-privacyidea#38]
We should support auth proc filters.
This way another auth source can first authenticate the user (e.g.) LDAP and in a second step an additional authentication will be run against privacyIDEA.

Yubikey auth proc does it this way:
https://github.com/simplesamlphp/simplesamlphp-module-yubikey/tree/master/lib/Auth/Process

[ ] We need to also provide the UI!?

Here is the basic concept
https://simplesamlphp.org/docs/stable/simplesamlphp-authproc

Todo: Discuss

**Comment by cornelinux** [comment]
I started a branch 
https://github.com/privacyidea/simplesamlphp-module-privacyidea/tree/38/authprocfilter

**Comment by Mipronimo** [comment]
@cornelinux can you please have a look at this: https://github.com/privacyidea/simplesamlphp-module-privacyidea/commit/a3762b4eac3c77fef2283469ef9aa81729013745
