### ISSUE TITLE
allow users to login without 2FA (decision in privacyIDEA)

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/simplesamlphp-module-privacyidea#41]
With the authproc filter we should be able to allow some users to login without 2FA. I.e. do not display the 2nd Dialog to enter the OTP value to the users.

This decision could be made by the privacyIDEA server using policies like "passOnNoUser" or "passOnNoToken".

To achieve this, the authproc filter needs to communicate with the privacyIDEA server *before* the Dialog is displayed to the user. We can do this via the endpoint ``/validate/check`` or via the endpoint ``validate/triggerchallenge``.

Using the triggerchallenge we can also add the possibility to also login with SMS or Email.

Unfortunately "triggerchallenge" currently does not support the "passOnNoUser".

**Comment by Mipronimo** [comment]
@cornelinux https://github.com/privacyidea/simplesamlphp-module-privacyidea/commit/2b002be9a6c7a1c2d1483321d572264b4cdb8ddb is able to do that for a stored user without token.

**Comment by cornelinux** [comment]
@Mipronimo  Nice! I added some comments.

**Comment by Mipronimo** [comment]
Forget the old one. I did it in a much better way now. Please have a look https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/57

**Comment by Mipronimo** [comment]
Because of all new branches we published, it is easier to show a new solution. https://github.com/privacyidea/simplesamlphp-module-privacyidea/commit/5767e31ccd759ad39c9e6f03a8f209ef5da3e934
