### ISSUE TITLE
Check client IP in authproc

### ISSUE THREAD

**Issue by Mipronimo** [privacyidea/simplesamlphp-module-privacyidea#42]
With the branch [addEnabledKey](https://github.com/privacyidea/simplesamlphp-module-privacyidea/tree/addEnabledKey), we can enable or disable 2FA in some situations. If we want to enable 2FA if the user is not in the local network, we can check this in another authproc filter.

Possible config for such a new filter class could be:

~~~~php
exclude2FAIPs = array("192.168.1.2", "10.0.0.0/29", "172.16.0.1/24");
~~~~

**Comment by Mipronimo** [comment]
https://github.com/privacyidea/simplesamlphp-module-privacyidea/commit/48aa4554ab3b229e6656e18a82bfae80ca93e959 gives the possibility to disable a range of ips for 2FA. For that you have to enable an authproc filter
~~~~php
        24 => array(
          'class' => 'privacyidea:checkClientIP',
          'excludeClientIPs' => array("10.1.0.0", "10.1.255.255"),
        ),
~~~~
This disables 2FA for all IPs in the range from 10.1.0.0 to 10.1.255.255

**Comment by cornelinux** [comment]
@Mipronimo can this issue be closed?
