### ISSUE TITLE
Challenge response input field not displaying

### ISSUE THREAD

**Issue by droobah** [privacyidea/simplesamlphp-module-privacyidea#59]
When a RADIUS/SMS/Email token is used, the response field does not appear.  I believe it is related to $hideResponseInput being set to true by default but not being set back to false if the challenge does not contain a u2f token.

**Comment by Mipronimo** [comment]
Sorry for my late response. I didn't saw this issue.
I tested it right now and will work on it.

Thanks a lot for your comment!!

**Comment by Mipronimo** [comment]
The PR is now merged @droobah if you want to, you can test the update from the master branch.
Please let us know, if there are any problems.
