### ISSUE TITLE
U2F doesn't work on firefox (with the plugin)

### ISSUE THREAD

**Issue by reardencode** [privacyidea/simplesamlphp-module-privacyidea#7]
I have the firefox u2f addon installed, and it works to login to privacyIDEA.

It doesn't work with the simpleSAMLphp module though :(

**Comment by cornelinux** [comment]
Do you have any additional information?
Probably you have a problem with the u2f_facets.
https://www.youtube.com/watch?v=0VKFGSAlL80

**Comment by reardencode** [comment]
It doesn't appear to be a problem with u2f_facets - it works properly in Chrome.

The error we get from FireFox originates here: https://github.com/privacyidea/simplesamlphp-module-privacyidea/blob/master/www/js/u2f-api.js#L23

So there seems to be some incompatibility with the way the module is setting up the u2f API.

**Comment by cornelinux** [comment]
I was not aware, that firefox even supports u2f.

**Comment by reardencode** [comment]
It requires an add-on to support it:
https://addons.mozilla.org/en-US/firefox/addon/u2f-support-add-on/

The add-on works properly to login to the privacyIDEA server, but not for the simpleSAMLphp module.

**Comment by cornelinux** [comment]
I can not support this on an open source basis and in addition we are missing information.
This probably would have to be debugged in a remote session.
Taking a look at som u2f firefox plugin the comments on this plugin sound, as if such a plugin is extremely buggy.
