### ISSUE TITLE
www/loginform.php missing

### ISSUE THREAD

**Issue by gyp5y** [privacyidea/simplesamlphp-module-privacyidea#75]
Hi there. It looks like module is not working as authsource because of missing www/loginform.php file.
Fix it please.

**Comment by Mipronimo** [comment]
In https://github.com/privacyidea/simplesamlphp-module-privacyidea/commit/3216ffc559e313f9ac6a75e019ba44d36b6045cc and https://github.com/privacyidea/simplesamlphp-module-privacyidea/commit/47731cb9801b790f7e88a518319d1ffd0ac7fb70 we merged www/loginform and template/loginform.
This is months ago. And it worked after that so can you please add more information.
What is exactly happening in your case?

**Comment by gyp5y** [comment]
We've got simplesamlphp with privecyidea module (1.6) working. But decided to upgrade both to latest versions. Configs just copied from old version  to new one. And now SSOService.php is redirection authorization to /module.php/privacyidea/loginform.php?AuthState=<removed> and we got simplesaml 404 error page "The given page was not found. The reason was: The URL wasn't found in the module. The URL was: https://<domain>/module.php/privacyidea/loginform.php?AuthState=<long authstate ulencoded data>

**Comment by Mipronimo** [comment]
Okay I cannot reproduce that.

Can you please check the following things?

* Make sure, that your webserver is permitted to read the module.
* Check if your Apache or Nginx is configured correctly
* You said you are using your old configuration. Please make sure that you named the module directory the same way as you did before
* If everything seems to be correct: Please post your logfile here. It should contain additional information.

**Comment by gyp5y** [comment]
1. Module permissions is ok
2. Config wasn't changed for a long time. I've double checked and it looks ok:
`
        location / {
                alias /var/www/simplesamlphp/www/;
                location ~ \.php(/|$) {
                        fastcgi_split_path_info ^((?U).+\.php)(/?.+)$;
                        fastcgi_param PATH_INFO $fastcgi_path_info;
                        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                        fastcgi_param HTTPS on;
                        fastcgi_pass unix:/var/spool/php/php.sock;
                        fastcgi_index index.php;
                        include fastcgi_params;
                }
        }
`
3. I've made a clean install of simplesamlphp and privacyidea module. Only certs, metadata and relevant part of config.php was copied:
`
  'privacyidea' => array(
        'privacyidea:privacyidea',
        'privacyideaserver' => 'https://<privacyidea server domain>',
        'sslverifyhost' => True,
        'sslverifypeer' => True,
        'realm' => '<our realm here>',
//          'otpextra' => 1,
        'attributemap' => array(
                        'username' => 'uid',
                        'surname' => 'sn',
                        'givenname' => 'givenName',
                        'email' => 'mail',
                        'phone' => 'telephoneNumber',
                        'mobile' => 'mobile',
                        'inetUserStatus' => 'inetUserStatus',
                        'objectClass' => 'objectClass',
                        'cn' => 'cn',
                        'memberOf' => 'memberOf',
                ),
    ),
`
Here is relevant part of a log:
`
Nov  8 06:48:36 login-2 simplesamlphp[29591]: 6 [2226def69f] 10.9.18.173 SAML2.0 - IdP.SSOService: Accessing SAML 2.0 IdP endpoint SSOService
Nov  8 06:48:36 login-2 simplesamlphp[29591]: 4 [2226def69f] 10.9.18.173 The class or interface 'sspmod_core_Auth_UserPassBase' is now using namespaces, please use 'SimpleSAML\Module\core\Auth\UserPassBase' instead.
Nov  8 06:48:36 login-2 simplesamlphp[29591]: 6 [2226def69f] 10.9.18.173 SAML2.0 - IdP.SSOService: IdP initiated authentication: '<service>'
Nov  8 06:48:36 login-2 simplesamlphp[29591]: 4 [2226def69f] 10.9.18.173 The class or interface 'SimpleSAML_Auth_State' is now using namespaces, please use 'SimpleSAML\Auth\State'.
Nov  8 06:48:36 login-2 simplesamlphp[29591]: 4 [2226def69f] 10.9.18.173 The class or interface 'SimpleSAML_Utilities' is now using namespaces, please use 'SimpleSAML\Utilities'.
Nov  8 06:48:37 login-2 simplesamlphp[31725]: 6 [2226def69f] 10.9.18.173 Could not find file '/var/www/simplesamlphp/modules/privacyidea/www/loginform.php'.
Nov  8 06:48:37 login-2 simplesamlphp[31725]: 3 [2226def69f] 10.9.18.173 SimpleSAML\Error\NotFound: The requested page 'https://host.ourdomain.com/module.php/privacyidea/loginform.php?AuthState=_fe137a2cd525d9245aa6bc86e0f60b1bf29aece70b.ourdomain.com.php.ourdomain.com.ourdomain.com.jsp.jspa' could not be found. The URL wasn't found in the module.
Nov  8 06:48:37 login-2 simplesamlphp[31725]: 3 [2226def69f] 10.9.18.173 Backtrace:
Nov  8 06:48:37 login-2 simplesamlphp[31725]: 3 [2226def69f] 10.9.18.173 1 /var/www/simplesamlphp/lib/SimpleSAML/Module.php:220 (SimpleSAML\Module::process)
Nov  8 06:48:37 login-2 simplesamlphp[31725]: 3 [2226def69f] 10.9.18.173 0 /var/www/simplesamlphp/www/module.php:9 (N/A)
Nov  8 06:48:37 login-2 simplesamlphp[31725]: 3 [2226def69f] 10.9.18.173 Error report with id c38f454a generated.
`
I've replaced our domain name with "ourdomain.com" for security reasons.

**Comment by Mipronimo** [comment]
Okay I installed now `simpleSAMLphp 1.17.7` with `simplesamlphp-module-privacyidea` from the master branch.
I tested the privacyidea authentication and it redirected me to `/module.php/privacyidea/otpform.php`, which worked without any problems.

**Comment by gyp5y** [comment]
After few days debbuging found that is was opcache issue (((
Sorry

**Comment by Mipronimo** [comment]
Good to hear, it's working now.
