### ISSUE TITLE
checkClientIP.php and tokenEnrollment.php have a different class prefix than privacyidea.php and serverconfig.php

### ISSUE THREAD

**Issue by lr** [privacyidea/simplesamlphp-module-privacyidea#81]
The following two classes have an uppercase "IDEA" in the class name:

- https://github.com/privacyidea/simplesamlphp-module-privacyidea/blob/master/lib/Auth/Process/checkClientIP.php
- https://github.com/privacyidea/simplesamlphp-module-privacyidea/blob/master/lib/Auth/Process/tokenEnrollment.php

While the following two classes have a lowercase "idea" in the class name:

- https://github.com/privacyidea/simplesamlphp-module-privacyidea/blob/master/lib/Auth/Process/privacyidea.php
- https://github.com/privacyidea/simplesamlphp-module-privacyidea/blob/master/lib/Auth/Process/serverconfig.php

The result is that, if you call an Auth/Process filter that renders a template **before** you call the privacyIDEA modules that have the uppercase "IDEA" in the class name, you get a PHP error similar to the following:

> ```PHP Fatal error:  SimpleSAML\Auth\ProcessingChain::resumeProcessing(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;sspmod_privacyIDEA_Auth_Process_checkClientIP&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /opt/simplesamlphp-1.18.3/lib/SimpleSAML/Auth/ProcessingChain.php on line 251```

I have verified that, if my Auth/Process filter never displays a template, then the error does not happen, however, if my filter displays a template, once the code eventually calls  `\SimpleSAML\Auth\ProcessingChain::resumeProcessing($state);`, the error is thrown (which results in a server 500 error).

I tried to work around this by changing the name of the filter class in the config from `privacyidea:checkClientIP` to `privacyIDEA:checkClientIP`, but when I did that, PHP threw the following error:

> ```An error has occurred. Caused by: Exception: Could not resolve 'privacyIDEA:checkClientIP': no class named 'SimpleSAML\Module\privacyIDEA\Auth\Process\checkClientIP' or 'sspmod_privacyIDEA_Auth_Process_checkClientIP'. error number: ...```

The only solution I could find was to the change the name of the class for checkClientIP.php and tokenEnrollment.php so that "privacyidea" is lowercase, e.g.:

`class sspmod_privacyidea_Auth_Process_checkClientIP extends SimpleSAML_Auth_ProcessingFilter {`

Do you know why two of the classes are named with `privacyIDEA` and the other two are named with `privacyidea`?

If you would like me to submit a PR for my changes, please let me know.

**Comment by NuvandaPV** [comment]
After long deliberation... I am just as baffled as you are. This seems like it is simply a bug. Please do submit a pull request.

**Comment by laclaro** [comment]
@lr Could you file a pull request?
