### ISSUE TITLE
evaluation of X-Forwarded-For for gettting client IP adress is bogus

### ISSUE THREAD

**Issue by spaceone** [privacyidea/simplesamlphp-module-privacyidea#86]
Every Proxy-Server/Gateway might add another value for `X-Forwarded-For` so that the value might be `127.0.1, 1.2.3.4, 5.6.7.8`. This is not considered in `lib/Auth/utils.php: sspmod_privacyidea_Auth_utils::getClientIP()`.

**Comment by laclaro** [comment]
You are right. Would you like to add a pull request for this issue?

**Comment by NuvandaPV** [comment]
We have proper handling for this in the core privacyIDEA project, however implementing this properly while being flexible enough is non-trivial and will require a non backward compatible change to the configuration, so it is worth putting some time into getting it right and making sure that it works the same way across all projects. Iirc we had decided to implement this as part of the new SDK, so all PHP-based projects can inherit the feature, not sure what the status of that is though.
