### ISSUE TITLE
unify optional checking filters

### ISSUE THREAD

**Issue by laclaro** [privacyidea/simplesamlphp-module-privacyidea#92]
We have checkClientIP and checkEntityID which check for client IP, entity and SAML attributes. On the long run, we may implement those three checks in a single configuration to realize condition combinations like

- IF clientIP = xyz AND attribute memberOf = asdf THEN disable
- IF entityID != xyz AND clientIP THEN enable
- IF memberOf = asdf THEN disable

**Comment by lukasmatusiewicz** [comment]
All procfilters unified since v2.0
